version: 2
job_common_node: &job_common_node
  docker:
    - image: cimg/node:14.17
  working_directory: ~/torus-embed
job_common: &job_common
  docker:
    - image: skyuppercut/node-puppeteer:latest
  working_directory: ~/torus-embed
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm install

jobs:
  build:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-embed
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus embed"
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - torus-embed
      - <<: *step_save_cache
  publish-npm:
    <<: *job_common_node
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run:
          name: "publish npm package"
          command: |
            . ./scripts/publishnpm.sh

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish-npm:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
